#!/bin/bash

echo "Running Hatstall"

git clone https://github.com/chaoss/grimoirelab-hatstall.git

# Try to copy a config file for SortingHat
cp shdb.cfg grimoirelab-hatstall/django-hatstall

cd grimoirelab-hatstall/django-hatstall

# Create the data models
python3 manage.py makemigrations
python3 manage.py migrate

# Create the initial admin user: admin/admin
PYTHONPATH=. django_hatstall/create_admin_superuser.py

# Run the Hatstall service
echo "Hatstall service ready at http://localhost:8000"
# python3 manage.py runserver 0.0.0.0:8000
gunicorn django_hatstall.wsgi --bind 0.0.0.0:8000
